name: Build WinBoat
permissions:
  contents: write
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - linux-only
          - guest-server-only

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && github.event_inputs.build_type != 'guest-server-only')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show build type
        run: if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then echo "Manual workflow triggered with build type: ${{ github.event_inputs.build_type }}"; else echo "Automatic workflow triggered by ${{ github.event_name }}"; fi
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Install dependencies
        run: npm ci
      - name: Build guest server and app
        run: npm run build:linux-gs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: dist/*

  guest-server-only:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event_inputs.build_type == 'guest-server-only'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show build type
        run: echo "Manual workflow triggered with build type: guest-server-only"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build guest server only
        run: bash build-guest-server.sh
      - name: Upload guest server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guest-server-artifacts
          path: guest_server/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event_inputs.build_type == 'all')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show build type
        run: if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then echo "Manual workflow triggered with build type: ${{ github.event_inputs.build_type }}"; else echo "Release workflow triggered by tag: ${{ github.ref_name }}"; fi
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install dependencies
        run: npm ci
      - name: Build guest server and app
        run: npm run build:linux-gs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip unpacked variant
        run: cd dist && zip -r winboat-linux-unpacked.zip linux-unpacked/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/winboat-linux-unpacked.zip
            dist/latest-linux.yml
            dist/linux-unpacked/resources/guest_server/winboat_guest_server.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
